// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zvx5NzZxzWJSp7_NzMzcOhC0PHp0SaU',
    appId: '1:222003182592:web:3697adafa0a4b88da42ce5',
    messagingSenderId: '222003182592',
    projectId: 'ride-sharing-9c176',
    authDomain: 'ride-sharing-9c176.firebaseapp.com',
    storageBucket: 'ride-sharing-9c176.firebasestorage.app',
    measurementId: 'G-KQETHMPJ12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpBw_DvDIJ16OZk1odua7q5hv0NcHy138',
    appId: '1:222003182592:android:851e41ecde3127c1a42ce5',
    messagingSenderId: '222003182592',
    projectId: 'ride-sharing-9c176',
    storageBucket: 'ride-sharing-9c176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCshO-IY8Jc-FcZKQhkeLb1vPraCkYUmws',
    appId: '1:222003182592:ios:98fc0c4417b2744fa42ce5',
    messagingSenderId: '222003182592',
    projectId: 'ride-sharing-9c176',
    storageBucket: 'ride-sharing-9c176.firebasestorage.app',
    iosBundleId: 'com.antigravity.rideshare.rideShareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCshO-IY8Jc-FcZKQhkeLb1vPraCkYUmws',
    appId: '1:222003182592:ios:98fc0c4417b2744fa42ce5',
    messagingSenderId: '222003182592',
    projectId: 'ride-sharing-9c176',
    storageBucket: 'ride-sharing-9c176.firebasestorage.app',
    iosBundleId: 'com.antigravity.rideshare.rideShareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2zvx5NzZxzWJSp7_NzMzcOhC0PHp0SaU',
    appId: '1:222003182592:web:a04b5780558c2f3ea42ce5',
    messagingSenderId: '222003182592',
    projectId: 'ride-sharing-9c176',
    authDomain: 'ride-sharing-9c176.firebaseapp.com',
    storageBucket: 'ride-sharing-9c176.firebasestorage.app',
    measurementId: 'G-J4DQ7JPXW0',
  );
}
